package threeprime

import (
	"fmt"
	bio "github.com/crmackay/gobioinfo"
	//"math"
	"bufio"
	"bytes"
	"testing"
)

// func threePLinkerTest(alignment *bio.PairWiseAlignment, read *bio.FASTQRead) bool {}
func TestThreePLinkerTest(t *testing.T) {
	fmt.Println("testing threePLinkerTest()")

	numRead := 6
	rawTestData := bytes.NewBufferString(`@HWI-ST560:155:C574EACXX:3:1101:2409:1942 1:N:0:
CACAGGGAGGACGATGCGGAAAAGAATGTGAATCATGGTGTTCTTGTGGTTGGCTATGGGACTCTTGATGGCAAAGATTACTGGCTTGTGAAAAAAGGGT
+
BBBFFFFFHHHHHFIJIJJJJJJJJIHIFIJJJJJJJJ=FGIJJJJHIJJJJHHHHFFFFFDEEEEDDDDDDDDDDDDDDDDDDDDD5?CCDCDD#####
@HWI-ST560:155:C574EACXX:3:1101:2433:1960 1:N:0:
AGCAGGGAGGACGATGCGGACAAGTCCCTGAGGAGCCCTTTGAGCCTGGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAA
+
BCCFFFFFHHHHHJJJJJJJIJJJGJIJJJIJJJJJJJJJJGJIJIJHHHGFFFFFFEEEEEEEDDDBDDDDDDDCDDDDDDDDDDDDDDDDDDD@B@DB
@HWI-ST560:155:C574EACXX:3:1101:2381:1976 1:N:0:
AGCAGGGAGGACGATGCGGTGATGTTCACAGTGGCTAAGTTCCGCGGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAA
+
BCCFFFFFHHHHHIJJJJJJJJJIIHIIJJJFHJJJJJJJJJJJJJJHHFFFFFFEEEEEEEDDDDDDDDDDCDDBBBDDDDDDDDCDDDDDDD9BB>BD
@HWI-ST560:155:C574EACXX:3:1101:2403:1977 1:N:0:
GCTAGGGAGGACGATGCGGCTAAGTGGTTGGAACCCGATTGCCTCTCTGGAGCGTGTCAGTCACTTCCAGCGGGTGTCAGTCACTTCCAGCGGTCGTATG
+
@@@FFFFFHHGHHJJJJJJGIEFHFHGDHGIEGGHIIJIICHHIJHEFHGDDDCDD@BCCDDDDDDA@CDDDDD@><ACDDCCCCCC>CC?>B9@B>833
@HWI-ST560:155:C574EACXX:3:1101:2425:1982 1:N:0:
GTGAGGGAGGACGATGCGGTTGTGTGAGAACTGAATTCCATAGGCTGTGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAA
+
CCCFFFFFHHFHHIJJJJJIJIGIIJJJFGIIIIIJJJG<FHEHIJIGIHGHJFIHHHHHHFFFFEDDDB@=?CD@ABBBDDDDCCDDC@DDDDDDB@BB
@HWI-ST560:155:C574EACXX:3:1101:3331:1961 1:N:0:
GTTCCATCAACATCATAGCCAGATGCCCAGAGATTAGAGCGCATGACAAGTAAAGGACGGTTGTCAGCGTCATAAGAGGTTTTACCTCCAAATGAAGAAA
+
CCCFFBFFFHHGHJIIJIIJJJJJIJIJJJJIJJJJGJIIJJJJJJJJIJGHIIHEHIIIHGHGFFFFFDDDDEDDDDDCBDDDDDDDDCDDDCAC::AC
@HWI-ST560:155:C574EACXX:3:1101:1179:1979 1:N:0:
AGCAGGGAGGACGATGCGGGTCAGTCACTTCCAGCGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAACAATATAATAACA
+
@@CFFFFFDHDHFIGIGHIF?DHH?FGIJIIIIIII;FAEGC@EEHHG9EDFFDB'9;8ACCCAB;B8<:>343>483:A####################
`)

	testReads := make([]bio.FASTQRead, numRead)
	//var err error
	scanner := bio.FASTQScanner{Scanner: bufio.NewScanner(rawTestData), File: nil}

	for i := 0; i < numRead; i++ {
		testReads[i], _ = scanner.NextRead()
	}

	subject := bio.NewDNASequence("GTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTG")

	type testGroup struct {
		alignment      bio.PairWiseAlignment
		read           bio.FASTQRead
		expectedResult bool
	}

	// TODO: need to add a few falses to the test sequence
	expectedResults := []bool{true, true, true, true, true, false, true}

	testSet := make([]testGroup, numRead)

	for i, read := range testReads {
		testSet[i].read = read

		testSet[i].alignment = read.Sequence.SG3pAlign(subject.Sequence)
		testSet[i].expectedResult = expectedResults[i]
	}

	for i, elem := range testSet {
		if i < 6 {
			result := threePLinkerTest(elem.alignment, elem.read, 1)
			if result != elem.expectedResult {
				t.Error(
					"got:",
					result,
					", expected:",
					elem.expectedResult,
					"for sequence: ",
					elem.read.ID,
					", here is the alignment: ", "\n",
					elem.alignment.GappedQuery, "\n",
					elem.alignment.AlignmentRepresentation, "\n",
					elem.alignment.GappedSubject, "\n",
				)
			}
		}

	}

}
