package switchblade

import (
	//"fmt"
	bio "github.com/crmackay/gobioinfo"
	"strings"
	"testing"
)

func makeTestRead(input string) (read bio.FASTQRead) {

	lines := strings.Split(input, "\n")

	ln1 := lines[0]
	ln2 := lines[1]
	ln3 := lines[2]
	ln4 := lines[3]

	newRead := bio.FASTQRead{
		ID: ln1,
		DNASequence: bio.DNASequence{
			Sequence: bio.NucleotideSequence([]rune(ln2)),
		},
		Misc: ln3,
		PHRED: bio.PHRED{
			Encoded:  []rune(ln4),
			Decoded:  nil,
			Encoding: "illumina_1.8",
		},
	}
	newRead.PHRED.Decode()
	return newRead
}

func makeTestAlignmentSet(read bio.FASTQRead, subject bio.DNASequence) alignmentSet {
	return alignmentSet{
		alignment: read.Sequence.Align(subject.Sequence),
		query:     read,
		subject:   subject,
	}
}

func TestTrim3p(t *testing.T) {

	//	testSubject := bio.DNASequence{Sequence: []rune("GTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTGCTTG")}
	/*
		testStrings := []string{
			"@HWI-ST560:155:C574EACXX:3:1101:2012:1985 1:N:0:\nAGCAGGGAGGACGATGCGGTTGTGATATAATACAACCTGCTAAGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAAAAA\n+\n@CCFFFFFHHHHHIIIIIICDF?D@BBD<<??FHG?GIIIIEG@@A@CAFHIIEIEEH@AHFF9AB;?CCCA@3=A<ACA>@CCB@::ABBBBBBCBBBB",
			"@HWI-ST560:155:C574EACXX:3:1101:2168:1987 1:N:0:\nAGCAGGGAGGACGATGCGGTACAGATCACATTGCCAGGGATTACCACAGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAA\n+\n@CCFFFFFHHHGHIJJJJJJJGJJFJGDHIJJIIJJJIIGGIGEHIJIJJGIJJGHAHCHEEEFFBC:B?DBDCCA@>BDDBCD@ACCABDCCBB#####",
			"@HWI-ST560:155:C574EACXX:3:1101:2074:1991 1:N:0:\nGTGAGGGAGGACGATGCGGCTGAGTAGCTTATCAGACTGATGTTGACGTGTCAGTCACTTCCAGCGGTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAA\n+\nBCCFFFFFHHHHHJJJJJJIJJJIDHIJJIGGGJIIJJJJIJIJFJJJJJJHGHHHHFFFFFFDECDDDDDDDDDCBBDDDDDDDDDDACDDDDDDDDDD",
			"@HWI-ST560:155:C574EACXX:3:1101:2214:1998 1:N:0:\nAGCAGGGAGGACGATGCGGAACTGATGTCTAAGTACGCACGGCCGGTACAGTGAAACTGCGAATGGCTCGTGTCAGTCACTTCCAGCGGGCGTATGCCGT\n+\nCCCFFFFFHHHHHJJJJJJJJJJJJJJJJIIGHEIIJIGIGGIGFFCCDDECCDDDDDDDDDDDDCDCC-9?28A@>4@AAC3>4439B###########",
		}
	*/

	t.Error("test fails")
}

func TestAlignProbTrim(t *testing.T) {

}
